export const ADD_DISH_REQUEST = "ADD_DISH_REQUEST";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const ADD_DISH_FAILURE = "ADD_DISH_FAILURE";

export const FETCH_ALL_MENU_REQUEST = "FETCH_ALL_MENU_REQUEST";
export const FETCH_ALL_MENU_SUCCESS = "FETCH_ALL_MENU_SUCCESS";
export const FETCH_ALL_MENU_FAILURE = "FETCH_ALL_MENU_FAILURE";

export const FETCH_ITEM_REQUEST = "FETCH_ITEM_REQUEST"
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS"
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE"

export const ADD_TO_BASKET = "ADD_TO_BASKET"
export const DELETE_ITEM = "DELETE_ITEM";